dist:     trusty
sudo:     false
language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on GOFLAGS=-mod=vendor
git:
  depth: 1
  go_import_path: github.com/dmacvicar/terraform-provider-salt
install:        true
script:
  - make fmt-check
  - make vet-check
  - make lint-check
  - make tf-check
  - make test

