name: Tests
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'website/*'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'website/*'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {os: ubuntu-latest, go: 1.16}
          - {os: windows-latest, go: 1.16}
          - {os: macos-latest, go: 1.16}
    timeout-minutes: 10
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        run: |
          make tf-check
      - name: Build
        run: |
          make
      - name: Test
        run: |
          make test
      - uses: actions/upload-artifact@v2
        with:
          name: terraform-provider-salt-${{ matrix.os }}
          path: ${{ github.workspace }}/terraform-provider-salt*
